#!/usr/bin/env bash
# 生成 src/ui/brain-ui/biz-preview.bundle.js —— 公网静态预览页专用经典脚本包。
#
# 为什么不用 ES module：
#   <script type="module"> 是 CORS 请求，浏览器会带 Origin 头，被后端
#   Origin 门（api.js isAllowedOrigin）403 拦截。顶层导航 GET、CSS、
#   经典 <script> 都不带 Origin，走既有的 public path 规则正常放行。
#   本预览页零 API 调用（种子数据全在包内），不触碰任何后端安全控制。
#
# 用法：bash scripts/build-biz-preview.sh   （biz 源码改动后重新生成）
set -euo pipefail
cd "$(dirname "$0")/../src/ui/brain-ui"

{
  echo "/* AUTO-GENERATED by scripts/build-biz-preview.sh — 勿手改，改 biz-*.js 后重新生成 */"
  echo "(function(){'use strict';"
  echo "/* ==== biz-data.js ==== */"
  sed 's/^export //' biz-data.js
  echo "/* ==== biz-panel.js ==== */"
  sed 's/^export //' biz-panel.js
  echo "/* ==== biz.js ==== */"
  sed -e '/^import { BIZ_DATA } from/d' -e 's/^export //' biz.js
  echo "/* ==== boot ==== */"
  echo "document.body.insertAdjacentHTML('beforeend', createBizPanel());"
  echo "initBizPanel();"
  echo "setBizPanelMode(true, { source: 'preview' });"
  echo "})();"
} > biz-preview.bundle.js

echo "built: $(pwd)/biz-preview.bundle.js ($(wc -c < biz-preview.bundle.js) bytes)"
